import { Product } from "./datamodels/Products";

export const dataProducts: Product[] = [
  {
    name: "Dessert item",
    slug: "1",
    image: "../images/dessertImages/pic1.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "2",
    image: "../images/dessertImages/pic2.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "3",
    image: "../images/dessertImages/pic3.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "4",
    image: "../images/dessertImages/pic4.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "5",
    image: "../images/dessertImages/pic5.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "6",
    image: "../images/dessertImages/pic6.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "7",
    image: "../images/dessertImages/pic7.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "8",
    image: "../images/dessertImages/pic8.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "9",
    image: "../images/dessertImages/pic9.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "10",
    image: "../images/dessertImages/pic10.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "Dessert item",
    slug: "11",
    image: "../images/dessertImages/pic11.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
];
