import { Product } from "./datamodels/Products";

export const dataProducts: Product[] = [
  {
    name: "พายสับปะรด",
    slug: "1",
    image: "../images/dessertImages/pic1.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "ชิฟฟรอนมะพร้าวอ่อน",
    slug: "2",
    image: "../images/dessertImages/pic2.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "เค้กโรล",
    slug: "3",
    image: "../images/dessertImages/pic3.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "คุ๊กกี้เสี่ยงทาย",
    slug: "4",
    image: "../images/dessertImages/pic4.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "เอเคล",
    slug: "5",
    image: "../images/dessertImages/pic5.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "บราวนี่",
    slug: "6",
    image: "../images/dessertImages/pic6.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "โมจิงาดำ",
    slug: "7",
    image: "../images/dessertImages/pic7.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "ขนมปังสังขยา",
    slug: "8",
    image: "../images/dessertImages/pic8.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "ดอกลำดวน",
    slug: "9",
    image: "../images/dessertImages/pic9.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "เค้กกล้วยหอม",
    slug: "10",
    image: "../images/dessertImages/pic10.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "พายสับปะรด",
    slug: "11",
    image: "../images/dessertImages/pic11.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "พายเนยสด",
    slug: "12",
    image: "../images/dessertImages/pic12.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "ขนมปังไส้กรอก",
    slug: "13",
    image: "../images/dessertImages/pic13.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "คุ๊กกี้ช็อกโกแลตชิฟ",
    slug: "14",
    image: "../images/dessertImages/pic14.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "คุ๊กกี้เนยสด",
    slug: "15",
    image: "../images/dessertImages/pic15.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
  {
    name: "คุ๊กกี้สิงคโปร์",
    slug: "16",
    image: "../images/dessertImages/pic16.jpg",
    category: "Dessert",
    brand: "Dessert",
    price: 60,
    countInstock: 100,
    description: "Fresh",
    rating: 5,
    numReviews: 10,
  },
];
